# Generated by Django 2.1.5 on 2019-11-24 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_auto_20191123_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todoApp.User'),
            preserve_default=False,
        ),
    ]
